### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by samachr** [flotwig/chromium-downloads#34]
It appears that the service backing https://chromium.cypress.io/ is currently down, getting 503s at https://chromium-downloads.herokuapp.com/builds

**Comment by samachr** [comment]
Tagging who appear to be the active maintainers for visibility into an outage: @colebrumley @tgriesser

**Comment by colebrumley** [comment]
Thank you for the report @samachr and @marcelrebmann and apologies for the delay in responding. The data source that drives this tool has been decommissioned, and the successor service isn't a clear 1:1 port so this will take us some time to resolve. I'll update this issue when we have a path forward.

**Comment by jennifer-shehane** [comment]
I'd just like to note that you can use https://vikyd.github.io/download-chromium-history-version/#/ as an alternative

**Comment by jennifer-shehane** [comment]
Hi everyone, I figured this may be a good place to update since some people had interest in this services functionality. 

We intend to drop support for the chromium-downloads website and no longer maintain it. We want to focus our efforts more fully on our core products at Cypress. 

We recommend using an alternative to get Chromium binaries via Operating System like: https://vikyd.github.io/download-chromium-history-version/#/
